version: '3'
services:
    frontend:
        restart: unless-stopped
        image: staticfloat/nginx-certbot
        ports:
            - 80:80/tcp
            - 443:443/tcp
        environment:
            CERTBOT_EMAIL: conlontj@clarkson.edu
            # variable names are space-separated
            ENVSUBST_VARS: FQDN
            FQDN: fraud-app.clarksonmsda.org
        volumes:
          - ./conf.d:/etc/nginx/user.conf.d:ro
          - letsencrypt:/etc/letsencrypt
    app:
        container_name: app
        volumes:
            - ./app:/app
        build:
          context: .
          dockerfile: Dockerfile
        command: ["python", "__init__.py"]
        ports:
            - 5000:5000
volumes:
    letsencrypt: